FROM node:alpine AS builder

WORKDIR /frontend

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

FROM nginx:alpine-slim as prod

COPY nginx.conf /etc/nginx/templates/nginx.conf.template
COPY --from=builder /frontend/dist /usr/share/nginx/html

EXPOSE 8070

CMD ["nginx", "-g", "daemon off;"]
