services:
  backend:
    container_name: litestar-backend
    build: ./backend
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
     - ./backend:/app
    env_file:
      - .env

  frontend:
    container_name: vite-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    volumes:
     - ./frontend:/app
     - /app/node_modules
    env_file:
      - .env
    environment:
      - NGINX_PORT=${VITE_PORT}
      - CHOKIDAR_USEPOLLING=true 

  weaviate:
    container_name: weaviate
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.0
    command:
      - --host
      - 0.0.0.0
      - --port
      - "${WEAVIATE_PORT}"
      - --scheme
      - http
    ports:
      - "${WEAVIATE_PORT}:${WEAVIATE_PORT}"
      - 50051:50051
    restart: on-failure:0
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'
