services:
  backend:
    container_name: litestar-backend
    build: ./backend
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
     - ./backend:/app
    env_file:
      - .env

  frontend:
    container_name: vite-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    volumes:
     - ./frontend:/app
     - /app/node_modules
    env_file:
      - .env
    environment:
      - NGINX_PORT=${VITE_PORT}
      - CHOKIDAR_USEPOLLING=true 

  weaviate:
    container_name: weaviate
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.0
    command:
      - --host
      - 0.0.0.0
      - --port
      - "${WEAVIATE_PORT}"
      - --scheme
      - http
    ports:
      - "${WEAVIATE_PORT}:${WEAVIATE_PORT}"
      - 50051:50051
    restart: on-failure:0
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'

  db:
    image: postgres:latest
    container_name: postgres-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    restart: always

volumes:
  weaviate_data:
    driver: local
  pgdata:
    driver: local
